### ISSUE TITLE
Consider extracting EnsureDbUpToDate logic into shared project

### ISSUE THREAD

**Issue by joaofbantunes** [AspNetCoreFromZeroToOverkill/GroupManagement#11]
`EnsureDbUpToDate` (besides lacking the `Async` suffix) should probably be, in this form or in another that makes more sense, extracted into a shared project, as we'll probably use it in other projects with EF Core.

**Comment by romanolester** [comment]
Should we have a separate helpers/utilities project?

**Comment by joaofbantunes** [comment]
Yes. I can create a new repository.

My idea with this one would be to use something like this [AspNetCore.AsyncInitialization](https://github.com/thomaslevesque/AspNetCore.AsyncInitialization) package (we could role our own, but since someone already done it, we can take advantage of it.).

To make it easier to test if it's working, we can create the shared project in this solution for now, and then we'll move it to the new repository. What do you think?

Want to grab this one @romanolester? If so, I'll assign the issue to you.

**Comment by joaofbantunes** [comment]
The steps I had imagined for this one:
1. New project like `CodingMilitia.PlayBall.Shared.StartupTasks`
2. Implement an `IAsyncInitializer` to handle the migrations, using [AspNetCore.AsyncInitialization](https://github.com/thomaslevesque/AspNetCore.AsyncInitialization)
3. Create some `ServiceCollection` extensions to make it easier to register the initializer in DI
4. When everything is working as expected, we can extract the project to a repository to keep shared projects
5. Configure CI for the project (Cake script, build on Azure Pipelines, publish NuGet package)
6. Install NuGet package in the projects that use it [GroupManagement](https://github.com/AspNetCoreFromZeroToOverkill/GroupManagement) and [Auth](https://github.com/AspNetCoreFromZeroToOverkill/Auth)

**Comment by romanolester** [comment]
Yes I want this one. Just please help me with the initial creation of the repo and project as I don't want to mess up with your naming convention 😊

**Comment by joaofbantunes** [comment]
- [x] #16 - Create (temporary) CodingMilitia.PlayBall.Shared.StartupTasks project
- [ ] #19 - Implement an `IAsyncInitializer` to handle the migrations 
- [ ] #20 - Create some `ServiceCollection` extensions to make it easier to register the initializer in DI
- [ ] #21 - When everything is working as expected, we can extract the project to a specific repository with some simple shared projects
- [ ] #22 - Create Cake build script
- [ ] #23 - Configure Azure Pipelines
- [ ] #24 - Install NuGet package in the projects that use it [GroupManagement](https://github.com/AspNetCoreFromZeroToOverkill/GroupManagement) and [Auth](https://github.com/AspNetCoreFromZeroToOverkill/Auth)

**Comment by joaofbantunes** [comment]
@romanolester created the project and a bunch of issues, to split the work into smaller steps.

**Comment by joaofbantunes** [comment]
Azure Artifacts doesn't allow for anonymous access to the feeds to install the packages (at least right now). Gotta think of an alternative 😐
